#!/bin/sh

envhost=${host:-127.0.0.1}
envport=${port:-80}
envkey=${key:-???}
envapi=${api:-/admin/api.php}
apicall=$(curl -s "$envhost:$envport$envapi?getForwardDestinations&auth=${envkey}" 2>/dev/null)
stats=$(echo $apicall | jq -r --indent 1 '.forward_destinations' | sed 's/[^"]*|//' | sed 's/:.*"/ipv6/g' | sed '1d' | sed '$ d' | sed 's/ //g' | sed -r 's/^.{1}//' | \
			 sed 's/[{}"]//g' | sed "s/#/-/" | awk -F':' '{gsub(/\./,"_",$1);print $1":"$2}')
#echo $stats
case $1 in
  config)
    echo "graph_title Pi-hole Forwarding Destination"
    echo "graph_vlabel %"
    echo "graph_category pihole"
    echo "graph_info This graph shows statistics on forwarding destinations."
    echo "graph_args --base 1000 -r --lower-limit 0 --upper-limit 100"
    echo 'graph_scale no'

    for stat in $stats
    do
        uid=$(echo $stat | sed 's/:.*//')
	echo $uid
        if [ $uid = "cache" ]; then
            echo "$uid.label $uid"
            echo "$uid.min 0"
	    echo "$uid.type GAUGE"
	    echo "$uid.draw AREA"
	else
            echo "$uid.label $uid"
            echo "$uid.min 0"
            echo "$uid.type GAUGE"
            echo "$uid.draw STACK"
	fi
    done
  exit 0;;
esac

for stat in $stats
do
    uid=$(echo $stat | sed 's/:.*//')
    value=$(echo $stat | sed 's/.*://' | sed 's/,//')
    echo "$uid.value $value"
done
